name: tallydash
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.0.0
  - plotly>=5.14.0
  - pytorch>=2.0.0
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - accelerate>=0.20.0
    - openai>=1.0.0
    - anthropic>=0.20.0
    - langchain>=0.1.0
    - streamlit>=1.28.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - python-dotenv>=1.0.0
    - requests>=2.31.0
    - tqdm>=4.65.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.0.0
    - mypy>=1.5.0
    - pre-commit>=3.3.0
    - ruff>=0.0.280